/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontSize: {
        mini: "12px",
        small: "13px",
        textSm: "14px",
        regular: "15px",
        textBase: "16px",
        textMd: "18px",
        textLg: "20px",
        textLs: "21.47px",
        titleSm: "22px",
        titleBase: "23px",
        titleMid: "24px",
        titleSemiMd: "26px",
        titleMd: "28px",
        titleXl: "30px",
        titleLg: "32px",
        titleXxl: "36px",
      },
      fontWeight: {
        extraLight: "300",
        light: "400",
        medium: "500",
        semiBold: "540",
        bold: "600",
        extraBold: "700",
      },
      colors: {
        primary: "#208876",
        light: "#dad6ff",
        black: "#000000",
        white: "#FFFFFF",
        gray: "#6C7278",
        lightGray: "#F9FAFB",
        coolGray: "#ACB5BB",
        deepGray: "#8c8e8f",
        violet: "#5015FF",
        lightGrayBeta: "#f1f1f1",
        darkGray: "#1A1C1E",
        softGray: "#E3E7EA",
        beige: "#F4F3ED",
        green: "#4ADE80",
        paleGray: "#DFDFE0",
        ultraLightGray: "#F8F8F8",
        mediumLightGray: "#E5E5E5",
        greenDark: "#007832",
        greenBright: "#2FEB7D",
        yellowDark: "#854d0e",
        yellowBright: "#FEF9C3",
        yellowPastel: "#FFF493",
        blackTransparent: "#00000033",
        softGreen: "#A3B8A2",
        lavenderLight: "#F6F3FF",
        mintGreen: "#B6E2C1",
        ashGray: "#ACB5BB",
        lightAshGray: "#EDF1F3",
        coral: "#E06763",
        periwinkleLight: "#EFF0F6",
        mediumGray: "#757575",
        neutralGray: "#D9D9D9",
        richBlack: "#1E1E1E",
        mintLight: "#EBFDF2",
        greenPrimary: "#0AAC53",
        silverGray: "#CDCDCD",
        lavenderUltraLight: "#F7F4FF",
        darkPurple: "#9215FF",
        orangePrimary: "#EB672F",
        rewardsOffered: "#2FEB7D",
        salmon: "#F9645F",
      },
      borderRadius: {
        custom: "10px",
        rounder: "5px",
        mediumRound: "7.62px",
      },
      height: {
        tiny: "15px",
        small: "43px",
        medium: "90px",
        mediumLarge: "100px",
        large: "120px",
        extraLarge: "138px",
      },
      width: {
        widthScaleSm: "123px",
        widthScaleSm2: "136px",
        narrowWidth: "379px",
        mediumWidth: "400px",
        widthScaleMd: "540px",
        widthScaleLg: "600px",
      },
      letterSpacing: {
        tight: "-0.01em",
        tighter: "-0.03em",
        "title-spacing": "-0.05em",
      },
      transitionProperty: {
        all: "all",
      },
      padding: {
        padXs: "5px",
        padXs2: "7px",
        padBase: "10px",
        padSm1: "11.5px",
        padSm: "13px",
        default: "14px",
        padMd: "15px",
        padMd2: "15.5px",
        padLg: "19px",
        padXl: "22.5px",
        padZone: "60px",
      },
      maxWidth: {
        popupMax: "600px",
        shellMax: "850px",
        widthScaleSm2: "136px",
      },
      minWidth: {
        minWidth: "120px",
        mediumMinWidth: "400px",
        largeMinWidth: "450px",
        wideMinWidth: "516px",
      },
      borderWidth: {
        thin: "1.6px",
      },
      minHeight: {
        boxSm: "300px",
        boxMd: "330px",
        boxLg: "353px",
      },
      lineHeight: {
        "tight-1.1": "1.1",
        "title-height": "32.6px",
      },
      spacing: {
        gapSm: "10px",
        medium: "60px",
      },
    },
    screens: {
      xxs: "380px",
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      desktop: "1440px",
      widescreen: "1536px",
      figmascreen: "1778px",
      fullhd: "1920px",
      ultrawide: "2560px",
      megawide: "3440px",
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};

